    - name: Build and push
      uses: docker/bake-action@v5
      with:
        files: docker-bake.hcl
        targets: custom-apps
        push: true
        set: |
          custom-apps.args.APPS_JSON_BASE64=${{ steps.prep.outputs.apps_json_base64 }}
          DOCKER_METADATA_OUTPUT_TAGS=${{ steps.meta.outputs.tags }}
      env:
        DOCKER_METADATA_OUTPUT_TAGS: ${{ steps.meta.outputs.tags }}
